blank_issues_enabled: true
contact_links:
  - name: 💬 General question or discussion
    url: https://github.com/ArtemioPadilla/JustSplit/discussions
    about: For questions, ideas, or open discussions about JustSplit
